[features]
seeds = false
skip-lint = false
[programs.devnet]
lottery = "b65W8DNjKxK7dEMfiqUJiC7YAbE4n52xfFWcA5XfyfX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./SeVembBtAPno8aJhUT15Hks2Fj4gJTpTgJRNTtG75cr.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
